[project]
name = "hyperwave"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "matplotlib>=3.9.4",
    "pandas>=2.3.3",
    "scipy>=1.13.1",
    "torch-hd>=5.8.4",
    "xarray>=2024.7.0",
    "xrft>=1.0.1",
]
